### PR TITLE
TypeError: datetime.datetime(2015, 4, 16, 20, 0) is not JSON serializable

### PR DESCRIPTION
**Pull request by barnumbirr**
Fixed TypeError caused by `u'lastchange': datetime.datetime(2015, 4, 15, 1, 10, 12)`
not being valid JSON.

### CODE REVIEW

**Comment by Rafiot** [comment]
What do you think about making it optional? I prefer to have a datetime object on the python object returned by the function, much nicer to do computations and other pythony things.

**Comment by barnumbirr** [comment]
Hi there,

You could definitely make it optional, it's all up to you. It's just that I'm not a big fan of returning 'invalid' JSON data. What would you think about:

```
if data:
        dt = datetime.fromtimestamp(data['state']['lastchange'])
        data['state']['lastchange'] = [dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second]
    else:
```

which returns `u'state': {u'lastchange': [2015, 4, 15, 1, 10, 12],`?
Is that something you would approve of?

Cheers.
M.

**Comment by kwisatz** [comment]
Hi,
I'm not sure I understand what you're trying to do? What is the use of having a json string that returns a function call instead of a formatted date by default? 

``` python
datetime.datetime()
```

Are you evaluating the json that you produce like that? Who or what is supposed to consume it?

**Comment by Rafiot** [comment]
Well, the Web API you query on https://level2.lu/* returns a json stream[1]. The Python API query the Web API and returns a python object to be consumed by other python code that will deal with the datetime object directly.

[1] https://github.com/syn2cat/Level2.lu

It makes sense to have a way to get a JSON object from python API but I don't think it should be the default.

**Pull request closed without merging**
